language: python

python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - make
  - make install
  - bin/pip3 install -r requirements-dev.txt

script:
  - PYTHONPATH=$PWD:$PYTHONPATH make test

notifications:
  email: false
